### ISSUE TITLE
В массиве items лишние повторения

### ISSUE THREAD

**Issue by cjbars** [usmetanina/web-reposit#3]
смотрите

```
1=>array('id'=>1,
    'title'=>'Start',
    'href'=>'index.php?page=1',
    'class'=>'mainmenu__items',
    'content'=>'.\assets\start.html'
```

у вас ключ =1
есть id = 1 (которое нигде не используется)
и есть 1 в ссылке index.php?page=1

Можете как то оптимизировать? 
Не проще ли внутри метода сделать проверку наличия ключа в массиве, и при его наличии выводить страницу?

**Comment by usmetanina** [comment]
надеюсь, я правильно вас поняла 891125407376c4bfe05e96c71545dd5cba79f702

**Comment by cjbars** [comment]
абсолютно точно!
